config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :senders do
    get 'daily_operations', to: "senders#daily_operations"
    get 'daily_transfers', to: "senders#daily_transfers"

    resources :receivers, only: [:index, :new, :create, :destroy, :show]
    resources :transfers, only: [:index, :new, :create] 

    resources :operations, only: [:index, :create]
    get 'operations/new_deposit', to: "operations#new_deposit", as: :new_deposit
    get 'operations/new_withdrawal', to: "operations#new_withdrawal", as: :new_withdrawal
  end

  resources :employees

  get '/transfers/search', to: "transfers#search", as: :search_transfers
  post '/transfers/search', to: "transfers#pending", as: :pending_transfers
  get '/transfers/:id/complete', to: "transfers#get_code", as: :get_transfer_code
  post '/transfers/:id/complete', to: "transfers#complete_transfer", as: :complete_transfer

  get '/login', to:"logins#new"
  post '/login', to:"logins#create"
  get '/logout', to:"logins#destroy"

  get '/dashboard', to:"pages#dashboard"
  get '/transfers/daily_amounts', to:"transfers#daily_amounts"
  get '/transfers/daily_number', to:"transfers#daily_number"
  get '/operations/daily_amounts', to:"operations#daily_amounts"
  get '/operations/daily_number', to:"operations#daily_number"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_one :user, :as => :userable
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_admin

  def new
    @user = User.new
  end

  def create
    employee = Employee.new(employee_params)
    if employee.save
      @user = User.new(user_params)
      @user.userable = employee
      if @user.save
        flash[:success] = "Empleado creado exitosamente."
        redirect_to dashboard_path
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    employee = Employee.find(params[:id])
    employee.user.destroy
    employee.destroy
    flash[:success] = "Se eliminó correctamente al empleado."
    redirect_to :back
  end

  def index
    @employees = Employee.where.not(id: current_user.userable_id)
    respond_to do |format|
      format.html
      format.json { render :json => @employees.to_json }
      format.xml { render :xml => @employees.to_xml } 
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :last_name, :mail, :password)
    end

    def employee_params
      params.require(:employee).permit(:is_admin)
    end
end

app/views/employees/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Mail</th>
      <th>Rol</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% employees.each do |employee| %>
      <tr>
        <td>
          <%= employee.user.name %> <%= employee.user.last_name %>
        </td>
        <td><%= employee.user.mail %></td>
        <td><%= employee.is_admin ? 'Administrador' : 'Cajero' %></td>
        <td>
          <%= link_to(employee_path(employee.id), method: :delete, class: "link-unstyled") do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/index.html.erb
<%= render partial: "index", locals: {employees: @employees} %>

app/views/employees/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
    <%= form_for(@user, url: employees_path) do |f| %>
      <h2>Agrega un empleado</h2>
      <hr class="colorgraph">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.label :name, 'Nombre' %>
            <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Nombre', required: true %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.label :last_name, 'Apellido' %>
            <%= f.text_field :last_name, class: 'form-control input-lg', placeholder: 'Apellido', required: true %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <%= f.label :mail, 'Mail' %>
            <%= f.email_field :mail, class: 'form-control input-lg', placeholder: 'E-Mail', required: true %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <%= f.label :password, 'Contraseña' %>
            <%= f.password_field :password, class: 'form-control input-lg', placeholder: 'Contraseña', required: true %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <label>
            <%= check_box("employee", "is_admin") %> &nbsp; El usuario es administrador 
            <label>
          </div>
        </div>  
      <hr class="colorgraph">
        <div class="row">
          <%= f.submit(@user.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
        </div>
    <% end %>
    <%= link_to "<< Atrás", dashboard_path %>
  </div>
</div>