config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :senders do
    get 'daily_operations', to: "senders#daily_operations"
    get 'daily_transfers', to: "senders#daily_transfers"

    resources :receivers, only: [:index, :new, :create, :destroy, :show]
    resources :transfers, only: [:index, :new, :create] 

    resources :operations, only: [:index, :create]
    get 'operations/new_deposit', to: "operations#new_deposit", as: :new_deposit
    get 'operations/new_withdrawal', to: "operations#new_withdrawal", as: :new_withdrawal
  end

  resources :employees

  get '/transfers/search', to: "transfers#search", as: :search_transfers
  post '/transfers/search', to: "transfers#pending", as: :pending_transfers
  get '/transfers/:id/complete', to: "transfers#get_code", as: :get_transfer_code
  post '/transfers/:id/complete', to: "transfers#complete_transfer", as: :complete_transfer

  get '/login', to:"logins#new"
  post '/login', to:"logins#create"
  get '/logout', to:"logins#destroy"

  get '/dashboard', to:"pages#dashboard"
  get '/transfers/daily_amounts', to:"transfers#daily_amounts"
  get '/transfers/daily_number', to:"transfers#daily_number"
  get '/operations/daily_amounts', to:"operations#daily_amounts"
  get '/operations/daily_number', to:"operations#daily_number"

end

app/views/pages/dashboard.html.erb
<div class="col-lg-12 col-sm-12">
  <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
      <div class="btn-group" role="group">
          <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
              <div class="hidden-xs">Dinero</div>
          </button>
      </div>
      <div class="btn-group" role="group">
          <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
              <div class="hidden-xs">Historial</div>
          </button>
      </div>
      <div class="btn-group" role="group">
          <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
              <div class="hidden-xs">Empleados</div>
          </button>
      </div>
  </div>
  <div class="well">
    <div class="tab-content">
      <div class="tab-pane fade in active" id="tab1">
        <h2>Dinero total: <span class="label label-info">$<%= @total %></span></h2>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
          <h3>Dinero por transferencias</h3>
          <%= line_chart transfers_daily_amounts_path, xtitle: 'Fecha', ytitle: 'Total', width: '700px', height: '400px'%>
          </div>
        </div>
        <hr class="colorgraph">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
          <h3>Dinero por operaciones</h3>
          <%= line_chart operations_daily_amounts_path, xtitle: 'Fecha', ytitle: 'Total', width: '700px', height: '400px'%>
          </div>
        </div>
      </div>
  
      <div class="tab-pane fade in" id="tab2">
        <h2>Transferencias</h2>
        <div class="row">
          <div class="col-md-3">
            <h3>Completadas: <span class="label label-success"><%= @completed %></span></h3>
          </div>
          <div class="col-md-3">
            <h3>Pendientes: <span class="label label-warning"><%= @pending %></span></h3>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
          <h3>Transferencias diarias</h3>
          <%= column_chart transfers_daily_number_path, xtitle: 'Fecha', ytitle: 'Número de transferencias', width: '700px', height: '400px'%>
          </div>
        </div>
        <hr class="colorgraph">
        <h2>Operaciones</h2>
        <div class="row">
          <div class="col-md-3">
            <h3>Depósitos: <span class="label label-success"><%= @deposits %></span></h3>
          </div>
          <div class="col-md-3">
            <h3>Retiros: <span class="label label-warning"><%= @withdrawals %></span></h3>
          </div>
        </div>
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
          <h3>Operaciones diarias</h3>
          <%= column_chart operations_daily_number_path, xtitle: 'Fecha', ytitle: 'Número de operaciones', width: '700px', height: '400px'%>
          </div>
        </div>
      </div>

      <div class="tab-pane fade in" id="tab3">
        <h2>Empleados</h2>
        <%= render partial: "employees/index", locals: {employees: @employees} %>
        <%= link_to(new_employee_path) do %>
          <button type="button" class="btn btn-success btn-lg">Crear empleado</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
  <div class="jumbotron">
    <h1>Bienvenido!</h1>
    <p>MON€YTRAN$ es el sistema más sencillo para mandar dinero a tus conocidos que se encuentran fuera de tu país.</p>
    <p><%= link_to "Regístrate", new_sender_path, class:'btn btn-primary btn-lg' %></p>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag("pages/ex.png", :alt => "rss feed",width: '150') %>
        <div class="caption">
          <h3>No importa el tipo de moneda</h3>
          <p>Tú puedes ingresar tu dinero en dólares y las demás personas lo van a recibir en la moneda del país en el que se encuentren sin nungún cargo extra.</p>
          <p><a href="/login" class="btn btn-primary" role="button">Log In</a> <a href="#" class="btn btn-default" role="button">Más Info</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag("pages/bank.png", :alt => "rss feed",width: '150') %>
        <div class="caption">
          <h3>Sin bancos</h3>
          <p>No necesitas estár afiliado a ningún banco para poder hacer las transferencias y no se te cobrará ninguna comisión extra por depósito ni por retiro.</p>
          <p><a href="/login" class="btn btn-primary" role="button">Log In</a> <a href="#" class="btn btn-default" role="button">Más Info</a></p>
        </div>
      </div>
    </div>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag("pages/security.png", :alt => "rss feed",width: '150') %>
        <div class="caption">
          <h3>Seguridad</h3>
          <p>Tu dinero se encuentra asegurado ya que nuestros grandes desarrolladores han habilitado muchos sistemas de seguridad para que tú estés tranquilo.</p>
          <p><a href="/login" class="btn btn-primary" role="button">Log In</a> <a href="#" class="btn btn-default" role="button">Más Info</a></p>
        </div>
      </div>
    </div>
  </div>
</html>