config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :senders do
    get 'daily_operations', to: "senders#daily_operations"
    get 'daily_transfers', to: "senders#daily_transfers"

    resources :receivers, only: [:index, :new, :create, :destroy, :show]
    resources :transfers, only: [:index, :new, :create] 

    resources :operations, only: [:index, :create]
    get 'operations/new_deposit', to: "operations#new_deposit", as: :new_deposit
    get 'operations/new_withdrawal', to: "operations#new_withdrawal", as: :new_withdrawal
  end

  resources :employees

  get '/transfers/search', to: "transfers#search", as: :search_transfers
  post '/transfers/search', to: "transfers#pending", as: :pending_transfers
  get '/transfers/:id/complete', to: "transfers#get_code", as: :get_transfer_code
  post '/transfers/:id/complete', to: "transfers#complete_transfer", as: :complete_transfer

  get '/login', to:"logins#new"
  post '/login', to:"logins#create"
  get '/logout', to:"logins#destroy"

  get '/dashboard', to:"pages#dashboard"
  get '/transfers/daily_amounts', to:"transfers#daily_amounts"
  get '/transfers/daily_number', to:"transfers#daily_number"
  get '/operations/daily_amounts', to:"operations#daily_amounts"
  get '/operations/daily_number', to:"operations#daily_number"

end

app/models/sender.rb
class Sender < ActiveRecord::Base
  has_and_belongs_to_many :receivers
  has_many :operations
  has_many :transfers
  has_one :user, :as => :userable

  def update_money(amount)
    self.update_attribute(:money, self.money + amount)
  end

  def enough_money?(amount)
    self.money + amount >= 0
  end

  def daily_operations
    self.operations.group_by_day(:created_at).sum(:amount)
  end

  def daily_transfers
    query = self.transfers.group(:receiver_id).group_by_day(:created_at).sum(:amount)
    receivers = Receiver.select(:id, :name, :last_name)
    query.each do |key, value|
      r = receivers.find(key[0])
      key[0] = r.name + " " + r.last_name
    end
    query
  end

  def is_admin
    false
  end

  def self.total
    Sender.sum(:money)
  end
end

app/controllers/senders_controller.rb
class SendersController < ApplicationController
  before_action except: [:new, :create] do
    authorize(get_id)
  end

  def new
    @user = User.new
  end

  def create
    sender = Sender.new()
    if sender.save
      @user = User.new(user_params)
      @user.userable = sender
      if @user.save
        flash[:success] = "Cuenta creada exitosamente."
        redirect_to root_path
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def show
    @user = current_user
	@bitcoin = GoogCurrency.usd_to_btc(@user.userable.money) 
    @pesos = GoogCurrency.btc_to_mxn(@bitcoin)
    respond_to do |format|
      format.html
      format.json { render :json => @user.to_json }
      format.xml { render :xml => @user.to_xml }
    end
  end

  def daily_operations
    render json: current_user.userable.daily_operations
  end

  def daily_transfers
    render json: current_user.userable.daily_transfers.chart_json
  end

  private
    def user_params
      params.require(:user).permit(:name, :last_name, :mail, :password)
    end

    def get_id
      params.has_key?(:sender_id) ? params[:sender_id] : params[:id]
    end
end

app/helpers/senders_helper.rb
module SendersHelper
end

app/views/senders/new.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
    <%= form_for(@user, url: senders_path) do |f| %>
      <h2>Regístrate <small>Es grátis</small></h2>
      <hr class="colorgraph">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.label :name, 'Nombre' %>
            <%= f.text_field :name, class: 'form-control input-lg', placeholder: 'Nombre', required: true %>
          </div>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6">
          <div class="form-group">
            <%= f.label :last_name, 'Apellido' %>
            <%= f.text_field :last_name, class: 'form-control input-lg', placeholder: 'Apellido', required: true %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <%= f.label :mail, 'Mail' %>
            <%= f.email_field :mail, class: 'form-control input-lg', placeholder: 'E-Mail', required: true %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
            <%= f.label :password, 'Contraseña' %>
            <%= f.password_field :password, class: 'form-control input-lg', placeholder: 'Contraseña', required: true %>
          </div>
        </div>
      </div>
      <hr class="colorgraph">
        <div class="row">
          <%= f.submit(@user.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
        </div>
    <% end %>
    <%= link_to "<< Atrás", root_path %>
  </div>
</div>

app/views/senders/show.html.erb
<div class="profile">
  <div class="col-lg-12 col-sm-12">
    <div class="card hovercard">
        <div class="card-background">
            <img class="card-bkimg" alt="nada" src="http://lorempixel.com/output/nature-q-c-400-400-1.jpg" >
        </div>
        <div class="card-info"> <span class="card-title"><%= @user.name %> <%= @user.last_name %></span>
        </div>
    </div>
    <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
        <div class="btn-group" role="group">
            <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-usd" aria-hidden="true"></span>
                <div class="hidden-xs">Dinero</div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
                <div class="hidden-xs">Historial</div>
            </button>
        </div>
        <div class="btn-group" role="group">
            <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-credit-card" aria-hidden="true"></span>
                <div class="hidden-xs">Receptores</div>
            </button>
        </div>
    </div>
    <div class="well">
      <div class="tab-content">
        <div class="tab-pane fade in active" id="tab1">
          <h2>Dinero</h2>
          <h3>Tu dinero actual es:</h3>$<%= @user.userable.money %> USD<br>
	      $<%= @pesos %> MXN<br>
          <br>
          <%= link_to(new_sender_transfer_path(@user.userable_id)) do %>
            <button type="button" class="btn btn-success btn-lg">Transferir</button>
          <% end %>
          <%= link_to(sender_new_deposit_path(@user.userable_id)) do %>
            <button type="button" class="btn btn-default btn-lg">Agregar Dinero</button>
          <% end %>
          <%= link_to(sender_new_withdrawal_path(@user.userable_id)) do %>
            <button type="button" class="btn btn-default btn-lg">Retirar Dinero</button>
          <% end %>
        </div>
        <div class="tab-pane fade in" id="tab2">
          <div class="row text-center">
            <div class="col-md-8 col-md-offset-2">
              <h3>Transferencias diarias</h3>
              <%= line_chart sender_daily_transfers_path(@user.userable_id), xtitle: 'Fecha', ytitle: 'Cantidad', width: '700px', height: '400px' %>
            </div>
          </div>
          <hr class="colorgraph">
          <div class="row text-center">
            <div class="col-md-8 col-md-offset-2">
              <h3>Operaciones diarias</h3>
              <%= line_chart sender_daily_operations_path(@user.userable_id), xtitle: 'Fecha', ytitle: 'Cantidad', width: '700px', height: '400px'%>
            </div>
          </div>
        </div>
        <div class="tab-pane fade in" id="tab3">
          <h2>Receptores</h2>
          <%= render partial: "receivers/index", locals: {receivers: @user.userable.receivers, sender: @user.userable} %>
          <%= link_to(new_sender_receiver_path(@user.userable_id)) do %>
            <button type="button" class="btn btn-success btn-lg">Agregar receptor</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>