config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :senders do
    get 'daily_operations', to: "senders#daily_operations"
    get 'daily_transfers', to: "senders#daily_transfers"

    resources :receivers, only: [:index, :new, :create, :destroy, :show]
    resources :transfers, only: [:index, :new, :create] 

    resources :operations, only: [:index, :create]
    get 'operations/new_deposit', to: "operations#new_deposit", as: :new_deposit
    get 'operations/new_withdrawal', to: "operations#new_withdrawal", as: :new_withdrawal
  end

  resources :employees

  get '/transfers/search', to: "transfers#search", as: :search_transfers
  post '/transfers/search', to: "transfers#pending", as: :pending_transfers
  get '/transfers/:id/complete', to: "transfers#get_code", as: :get_transfer_code
  post '/transfers/:id/complete', to: "transfers#complete_transfer", as: :complete_transfer

  get '/login', to:"logins#new"
  post '/login', to:"logins#create"
  get '/logout', to:"logins#destroy"

  get '/dashboard', to:"pages#dashboard"
  get '/transfers/daily_amounts', to:"transfers#daily_amounts"
  get '/transfers/daily_number', to:"transfers#daily_number"
  get '/operations/daily_amounts', to:"operations#daily_amounts"
  get '/operations/daily_number', to:"operations#daily_number"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MON€YTRAN$</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">MON€YTRAN$</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <% if current_user.userable_type == 'Sender' %>
            <li><%= link_to 'Perfil', sender_path(current_user) %></li>
          <% elsif current_user.userable.is_admin %>
            <li><%= link_to 'Dashboard', dashboard_path %></li>
          <% else %>
            <li><%= link_to 'Buscar', search_transfers_path %></li>
          <% end %>
        <% end %>
      </ul>
      <% if logged_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/logout">Log Out</a></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/login">Log In</a></li>
      </ul>
      <%end%>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= render partial: "shared/flash_messages", flash: flash %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>